---
title: "Plot ATC 1st Classes"
author: "Meera Y. Patel, M.D."
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: kate  
    code_folding: show #or hide
    df_print: paged
---

```{r, include = FALSE}
knitr::opts_chunk$set(comment = "##",
                      tidy = TRUE, #`styler` to use styler:style_text() to reformat code
                      tidy.opts = list(blank = FALSE, width.cutoff = 60),
                      echo = TRUE,
                      eval = TRUE,
                      cache = TRUE,
                      # cache.path = "reports/cache/",
                      child = NULL, #file/s to knit and then include,
                      collapse = FALSE, #collapse all output into a single block,
                      error = TRUE, #display error messages in doc. FALSE stops render when error is thrown
                      include = TRUE, #include chunk?
                      message = FALSE, #display code messages?
                      tidy = TRUE, #tidy code 
                      warning = FALSE, #include warnings?
                      results = "markup"
                        # "asis": passthrough results
                        # "hide": do not display results 
                        # "hold": put all results below all code
                      )
```

```{r setup}
library(amphora)
library(tidyverse)
conn <- pg13::local_connect()
```

```{r}
plot <- plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21600001)
htmlwidgets::saveWidget(widget = plot,
                        file = file.path(getwd(), "vignettes", "widgets", sprintf("%s", "ALIMENTARY TRACT AND METABOLISM.html")))
```


```{r}
 plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21600959)
```


```{r}
 plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21601237)
```


```{r}
 plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21601386)
```


```{r}
 plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21601907)
```


```{r}
 plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21602359)
```


```{r}
 plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21602681)
```


```{r}
 plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21602795)
```


```{r}
 plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21603550)
```


```{r}
 plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21603931)
```


```{r}
 plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21604180)
```


```{r}
 plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21604847)
```
 

```{r}
 plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21605007)
```


```{r}
 plot_atc_1st_class(conn = conn, vocab_schema = 'omop_vocabulary', atc_1st_concept = 21605212)
```

```{r}
pg13::dc(conn = conn)
```

